export type RoadmapStatus = "completed" | "in-progress" | "planned" | "future";
export type RoadmapCategory = "core" | "productivity" | "collaboration" | "analytics" | "integration" | "platform";

export interface RoadmapItem {
  id: string;
  title: string;
  description: string;
  detail: string;
  status: RoadmapStatus;
  category: RoadmapCategory;
  quarter: string;
  icon: string;
  highlights: string[];
  badge?: string;
}

export const CATEGORY_LABELS: Record<RoadmapCategory, string> = {
  core: "Core",
  productivity: "Productivity",
  collaboration: "Collaboration",
  analytics: "Analytics",
  integration: "Integration",
  platform: "Platform",
};

export const CATEGORY_COLORS: Record<RoadmapCategory, string> = {
  core: "#6366f1",
  productivity: "#f59e0b",
  collaboration: "#10b981",
  analytics: "#3b82f6",
  integration: "#8b5cf6",
  platform: "#ec4899",
};

export const ROADMAP_ITEMS: RoadmapItem[] = [
  // ── Completed ───────────────────────────────────────────────────────────────
  {
    id: "workspace-foundation",
    title: "Workspace Foundation",
    description: "Core workspace system with member roles, invitation flow, and permission isolation.",
    detail: "Built the foundational workspace layer that underpins all of Focura. Includes Owner/Admin/Member roles, workspace slugs for clean URLs, invitation via email, member management, and full workspace-level data isolation to prevent cross-tenant access.",
    status: "completed",
    category: "core",
    quarter: "Q4 2025",
    icon: "⬡",
    highlights: ["Owner / Admin / Member roles", "Email-based invitations", "Workspace slug URLs", "Cross-tenant data isolation"],
  },
  {
    id: "task-system",
    title: "Task Management System",
    description: "Full task lifecycle with status, priority, assignees, subtasks, due dates, labels, and recurrence.",
    detail: "The core task engine. Tasks support five status states, three priority levels, multi-assignee, due dates, rich descriptions, subtasks, color-coded labels, and recurring schedules. Three view modes — Project, Personal, and Workspace — plus list, board, and timeline presentations let each team member see exactly what they need.",
    status: "completed",
    category: "core",
    quarter: "Q4 2025",
    icon: "◉",
    highlights: ["5 status types + priority levels", "Subtask nesting & task recurrence", "Per-project labels with color", "Project / Personal / Workspace view modes"],
  },
  {
    id: "auth-system",
    title: "RS256 Authentication",
    description: "NextAuth + RS256 JWT token exchange with refresh, revocation, 2FA, and Google OAuth.",
    detail: "Enterprise-grade authentication. NextAuth manages sessions client-side while the Express backend is the sole authority for RS256 JWT signing. Tokens have 15-minute access expiry with 7-day refresh. Logout immediately revokes tokens via Redis JTI blacklisting. Google OAuth and two-factor authentication (TOTP) are included.",
    status: "completed",
    category: "platform",
    quarter: "Q4 2025",
    icon: "◐",
    highlights: ["RS256 JWT (private key server-only)", "Token revocation via Redis JTI", "Google OAuth + two-factor authentication", "Replay protection with HMAC timestamps"],
  },
  {
    id: "activity-feed",
    title: "Activity Feed & Audit Trail",
    description: "Permanent, timestamped log of every task and workspace mutation.",
    detail: "Every meaningful action in Focura — status changes, reassignments, comments, attachments, label updates — is logged to an immutable activity feed. Entries are attributed to users with exact timestamps. Workspace owners can view activity across all members.",
    status: "completed",
    category: "core",
    quarter: "Q1 2026",
    icon: "⚡",
    highlights: ["Task-level activity timeline", "Workspace-wide activity stream", "Permanent and uneditable entries", "Full user attribution"],
  },
  {
    id: "comments-mentions",
    title: "Comments & @Mentions",
    description: "Threaded task comments with @mention notifications and reply support.",
    detail: "Team communication lives inside tasks. Members can leave comments, reply to specific messages, and @mention teammates to trigger direct notifications. The mention system parses user references and delivers SSE notifications in real time.",
    status: "completed",
    category: "collaboration",
    quarter: "Q1 2026",
    icon: "◎",
    highlights: ["Threaded replies", "@mention with real-time notification", "Comment activity logging", "Soft-delete with history preserved"],
  },
  {
    id: "announcements",
    title: "Rich-Text Announcements",
    description: "Workspace announcements with custom format tokens, visibility controls, and pinning.",
    detail: "Admins can broadcast workspace-wide announcements using a rich-text editor with custom format tokens. Announcements support visibility scoping (all members or specific projects), pinning to keep critical updates visible, and live preview before publishing.",
    status: "completed",
    category: "collaboration",
    quarter: "Q1 2026",
    icon: "◇",
    highlights: ["Rich-text editor with format tokens", "Visibility scoping", "Pin to top", "Live preview"],
  },
  {
    id: "focus-mode",
    title: "Focus Mode",
    description: "Timed deep-work sessions linked to a single task with persistent banner and stats.",
    detail: "Focus Mode helps team members do distraction-free work. Starting a session pins the active task to a persistent banner visible across all pages. Sessions are timed, stats are tracked per user (total time, sessions, daily average), and a 30-second polling loop keeps stats fresh.",
    status: "completed",
    category: "productivity",
    quarter: "Q1 2026",
    icon: "◑",
    highlights: ["Persistent cross-page banner", "Session timer and stats", "Daily + total focus time tracking", "30s polling for live stats"],
  },
  {
    id: "sse-notifications",
    title: "Real-time SSE Notifications",
    description: "Server-Sent Events stream with per-project preferences and single-use token authentication.",
    detail: "Real-time notifications without WebSocket complexity. The backend maintains a persistent SSE connection per user, authenticated with a short-lived, single-use token minted per connection — access tokens never appear in URLs. Notifications fire for assignments, @mentions, meeting invites, announcement publishes, and automation triggers, with per-project preferences controlling the noise. Data-carrying heartbeats keep idle streams alive and the client auto-reconnects on drop.",
    status: "completed",
    category: "platform",
    quarter: "Q1 2026",
    icon: "▲",
    highlights: ["Per-user SSE stream with single-use tokens", "Task, mention, meeting & automation events", "Per-project notification preferences", "Auto-reconnect + data-carrying heartbeats"],
  },
  {
    id: "meetings",
    title: "Meetings Module",
    description: "Schedule team meetings, invite participants, and link them to projects.",
    detail: "The meetings module lets teams schedule discussions directly in Focura. Meetings attach to workspaces or projects for context. Participants receive SSE notifications with deep-link URLs built from workspace slugs. Past and upcoming meetings are listed chronologically.",
    status: "completed",
    category: "collaboration",
    quarter: "Q1 2026",
    icon: "◈",
    highlights: ["Project-linked meetings", "Participant invitations via SSE", "Slug-based notification deep links", "Chronological meeting list"],
  },
  {
    id: "feature-voting",
    title: "Feature Voting Board",
    description: "Community idea board with upvote counts, admin status management, and real-time counts.",
    detail: "Team members can propose feature ideas and vote on them. Vote counts update optimistically for instant feedback. Admins can mark items as Planned or Completed. The board surfaces the most-requested ideas to help leadership prioritize upcoming work.",
    status: "completed",
    category: "collaboration",
    quarter: "Q2 2026",
    icon: "✦",
    highlights: ["Optimistic vote count updates", "Admin status management (Planned/Completed)", "Idea submission by any member", "Priority surfacing for leadership"],
  },
  {
    id: "billing-paddle-integration",
    title: "Paddle Billing & Subscriptions",
    description: "Paddle-powered subscription management with plan changes, invoices, and webhooks.",
    detail: "Full subscription lifecycle via Paddle across four tiers — Free, Pro, Business, and Enterprise. Workspace owners can upgrade or downgrade plans with immediate effect and prorated billing. Webhooks handle subscription events (created, updated, canceled). Invoices are auto-generated and downloadable as PDF.",
    status: "completed",
    category: "platform",
    quarter: "Q2 2026",
    icon: "◆",
    highlights: ["Four tiers — Free / Pro / Business / Enterprise", "Plan upgrade / downgrade", "Prorated billing + Paddle webhooks", "PDF invoice downloads"],
  },
  {
    id: "redis-caching",
    title: "Redis Caching Layer",
    description: "Upstash Redis caching with workspace-aware invalidation and token revocation.",
    detail: "Response caching powered by Upstash Redis reduces database load on hot query paths. The invalidation strategy is workspace-aware — mutations clear only the caches of affected users. The same Redis instance handles JWT JTI revocation for instant logout.",
    status: "completed",
    category: "platform",
    quarter: "Q1 2026",
    icon: "⬟",
    highlights: ["Per-user cache invalidation", "JWT JTI revocation", "TLS-secured Upstash connection", "Optimistic update race condition handling"],
  },
  {
    id: "testing-suite",
    title: "Testing Suite",
    description: "4,400+ backend tests plus a frontend Vitest + RTL + MSW suite.",
    detail: "A comprehensive test suite across both repos. The backend runs 4,400+ unit and integration tests covering every module — access control, rate limiting, automations, billing, and more. The frontend covers all major data hooks with MSW API mocking, a createWrapper pattern for React Query cache seeding, and strict patterns: mutate() inside act(), waitFor() outside. jsdom is pinned to v24 for ESM compatibility.",
    status: "completed",
    category: "platform",
    quarter: "Q1 2026",
    icon: "⊕",
    highlights: ["4,400+ backend unit & integration tests", "Frontend Vitest + RTL + MSW", "MSW API mocking + query-cache patterns", "jsdom@24 + TransformStream polyfill"],
  },
  {
    id: "kanban-board",
    title: "Kanban Board View",
    description: "Drag-and-drop Kanban boards with execution controls, swimlane insights, and automation hooks.",
    detail: "A full visual Kanban board for projects and workspace tasks. Cards drag between columns, open inline detail, and sit in an execution control bar for batch operations. An insight footer summarizes column health and WIP pressure. Board drags update status through the standard status API, so activity logs and automation rules fire exactly as they do from the list view.",
    status: "completed",
    category: "core",
    quarter: "Q2 2026",
    icon: "▤",
    highlights: ["Drag-and-drop between columns", "Execution control bar for batch actions", "Insight footer with column health", "Board drags trigger automations & activity"],
  },
  {
    id: "calendar-scheduling",
    title: "Calendar & Scheduling View",
    description: "Monthly/weekly calendar with drag-and-drop rescheduling, day details, and workload insights.",
    detail: "The calendar plots task due dates, meetings, and focus sessions on monthly and weekly grids. Drag-and-drop rescheduling updates due dates in place. A day-details panel breaks down each day's load while the insights bar and burnout-trend charts surface busy periods and capacity pressure — so teams can plan without spreadsheets.",
    status: "completed",
    category: "productivity",
    quarter: "Q2 2026",
    icon: "▣",
    highlights: ["Monthly & weekly grids", "Drag-and-drop rescheduling", "Day details + insights bar", "Burnout & workload trend charts"],
  },
  {
    id: "project-planning",
    title: "Sprints, Milestones & Saved Views",
    description: "Project sections, sprint planning with burndown, milestones, saved views, and favorites.",
    detail: "Projects gained a full planning layer. Sections organize tasks into logical groups, sprints add scoped planning windows with burndown tracking, and milestones mark key delivery points. Saved views persist filter combinations per project, favorites pin frequent pages, and a timeline view plots tasks over time. Project access control restricts every one of these pages to project members.",
    status: "completed",
    category: "core",
    quarter: "Q2 2026",
    icon: "◒",
    highlights: ["Project sections & timeline view", "Sprint planning with burndown", "Milestone tracking", "Saved views + favorites"],
  },
  {
    id: "integrations-hub",
    title: "Workspace Integrations",
    description: "OAuth + webhook connectors — GitHub, Slack, Google Calendar, and Trello — with disconnect confirmation.",
    detail: "Workspace-level connectors link external tools to Focura. GitHub links pull requests and commits to tasks and auto-completes tasks on merge. Slack supports signature-verified webhooks, message-to-task creation, and challenge verification. Google Calendar and Trello connect via OAuth. Every connector surfaces connection state with explicit disconnect confirmation.",
    status: "completed",
    category: "integration",
    quarter: "Q2 2026",
    icon: "⧉",
    highlights: ["GitHub PR ↔ task linking, auto-complete on merge", "Slack webhooks with signature verification", "Google Calendar & Trello via OAuth", "Connect / disconnect with confirmation"],
  },
  {
    id: "templates-catalog",
    title: "Template Catalog",
    description: "Tier-gated project templates with community ratings and admin moderation.",
    detail: "A curated template catalog lets teams start projects from proven structures — sprint setups, content calendars, product roadmaps. Templates are tier-gated across plans, community members can rate them, and admins moderate the catalog from the admin dashboard. New-project creation flows straight from a chosen template.",
    status: "completed",
    category: "productivity",
    quarter: "Q2 2026",
    icon: "▧",
    highlights: ["Tier-gated template catalog", "Community ratings", "Admin moderation", "One-click project creation from template"],
  },
  {
    id: "offline-search",
    title: "Offline Support & Global Search",
    description: "Service worker + IndexedDB offline cache with mutation syncing, plus global search.",
    detail: "A service worker caches the app shell and data in IndexedDB so core workflows survive connection drops. An offline indicator shows state, and mutations made offline are queued and synced when connectivity returns. Global search indexes tasks, projects, and members across workspaces from a single entry point.",
    status: "completed",
    category: "platform",
    quarter: "Q2 2026",
    icon: "⌕",
    highlights: ["Service worker + IndexedDB cache", "Offline mutation queue & sync", "Offline indicator UI", "Global cross-workspace search"],
  },
  {
    id: "security-hardening",
    title: "Security Hardening & Rate Limiting",
    description: "Tier-based per-user rate limits, two-factor authentication, session heartbeat, and CSRF protection.",
    detail: "Every API module sits behind fail-closed, per-user rate limits that scale with the workspace plan. Two-factor authentication (TOTP) secures accounts, sessions track activity heartbeats and can be revoked from the security page, and state-changing routes enforce CSRF. SSE notification streams authenticate with short-lived single-use tokens, and logouts blacklist JWTs instantly via Redis.",
    status: "completed",
    category: "platform",
    quarter: "Q2 2026",
    icon: "◭",
    highlights: ["Tier-based per-user rate limiting (fail-closed)", "Two-factor authentication (TOTP)", "Session heartbeat + revocation", "CSRF + SSE token hardening"],
  },
  {
    id: "ai-assistant",
    title: "AI Assistant",
    description: "Goal breakdown, daily plans, weekly insights, comment assist, and meeting summaries.",
    detail: "An AI layer embedded across the product. Describe a goal and get a broken-down task plan; receive a daily plan each morning and weekly insights into progress and focus; get suggested comments while writing task updates; and read automatic meeting summaries. AI usage is metered with a quota badge, gated to eligible plans, and admins can override limits per workspace.",
    status: "completed",
    category: "productivity",
    quarter: "Q3 2026",
    icon: "✧",
    highlights: ["Goal → task breakdown", "Daily plans & weekly insights", "Comment assist + meeting summaries", "Quota tracking + admin overrides"],
  },
  {
    id: "automation-engine",
    title: "Automation Engine",
    description: "No-code rules — triggers, actions, and a background worker — plus manual run-now testing.",
    detail: "Automations let teams encode workflows: when a task is created or its status changes, assign it, set its priority, or notify members — up to five actions per rule. Rules are workspace-scoped, editable only by owners/admins, capped by plan (10 Free / 50 Pro / 200 Business / unlimited Enterprise), and executed by a BullMQ worker that is loop-safe and burst-capped. A Run now button tests any rule against a real task. Managed from Workspace Settings → Automations.",
    status: "completed",
    category: "core",
    quarter: "Q3 2026",
    icon: "⚙",
    highlights: ["Task-created & status-changed triggers", "Assign, priority & notify actions", "BullMQ worker — loop-safe, burst-capped", "Plan-based limits + run-now testing"],
  },
  {
    id: "analytics-wellness",
    title: "Analytics & Wellness",
    description: "Project KPIs, completion trends, deadline risk, CSV export, and burnout & capacity tracking.",
    detail: "Analytics moved from vanity charts to decision support. Project dashboards show KPI cards, completion trends, deadline-risk panels, priority distribution, and member leaderboards; workspace analytics add date-range filters and CSV export. On the human side, wellness and capacity tracking feed a burnout dashboard that helps leads spot overload before it becomes attrition.",
    status: "completed",
    category: "analytics",
    quarter: "Q3 2026",
    icon: "◬",
    highlights: ["Project KPIs, trend & deadline-risk panels", "Member leaderboards", "Date-range filters + CSV export", "Wellness, capacity & burnout dashboard"],
  },
  {
    id: "privacy-suite",
    title: "Privacy & Data Controls",
    description: "Self-service data export, account deletion with ownership guards, and a cookie-consent banner.",
    detail: "Privacy promises became self-service. Users can export a complete JSON bundle of their data (profile, workspaces, projects, tasks, comments, focus sessions, time entries, notifications, activity) delivered by email, or delete their account — deletion is blocked with a clear reason when the user is the sole owner of a workspace with other members, and revokes every session immediately. A cookie-consent banner gates Google Analytics behind explicit opt-in.",
    status: "completed",
    category: "platform",
    quarter: "Q3 2026",
    icon: "◫",
    highlights: ["One-click data export (JSON bundle)", "Account deletion with ownership-transfer guards", "Instant session revocation on delete", "Cookie-consent banner for analytics"],
  },
  {
    id: "admin-dashboard",
    title: "Admin Dashboard",
    description: "Workspace stats, template moderation, plan management, and AI-limit overrides for operators.",
    detail: "An operator console for Focura administrators: platform-wide workspace and user statistics, template catalog moderation, workspace plan management (including the Enterprise tier), and per-workspace AI-limit overrides. Authorization is role-checked so only genuine admins reach the console.",
    status: "completed",
    category: "platform",
    quarter: "Q3 2026",
    icon: "◨",
    highlights: ["Platform-wide workspace & user stats", "Template catalog moderation", "Plan & Enterprise management", "AI-limit overrides + role checks"],
  },

  // ── In Progress ──────────────────────────────────────────────────────────────
  {
    id: "time-tracking",
    title: "Time Tracking",
    description: "Time entries on tasks and calendar days with reports, timesheets, and billable-hour tagging.",
    detail: "The data layer is live — a TimeEntry model with categories backs calendar day details, analytics, and workspace-usage queries, and data exports already include time entries. The remaining work is the user-facing surface: manual time entry on tasks, per-task summaries, and workspace-level reports with billable-hour tagging by member and project.",
    status: "in-progress",
    category: "productivity",
    quarter: "Q3 2026",
    icon: "◔",
    badge: "In Progress",
    highlights: ["TimeEntry model with categories (backend live)", "Calendar day-detail integration", "Per-task time summaries", "Reports & billable hours (in progress)"],
  },

  // ── Planned ──────────────────────────────────────────────────────────────────
  {
    id: "microsoft-teams",
    title: "Microsoft Teams Integration",
    description: "Teams connector following the Slack pattern — message-to-task, digests, and slash commands.",
    detail: "With Slack, GitHub, Google Calendar, and Trello shipped, Teams is the natural next connector. Plan: link channels to workspaces, turn messages into tasks, deliver daily digests, and support slash commands — reusing the signature-verified webhook and OAuth infrastructure already in place.",
    status: "planned",
    category: "integration",
    quarter: "Q4 2026",
    icon: "⊞",
    badge: "Planned",
    highlights: ["Channel ↔ workspace linking", "Message → task creation", "Daily digest delivery", "Slash commands"],
  },
  {
    id: "ai-predictive-scheduling",
    title: "AI Predictive Scheduling",
    description: "Velocity-based deadline suggestions and workload-aware priority recommendations.",
    detail: "The AI assistant ships goal breakdown and daily/weekly insights; the next layer adds prediction. Using historical throughput, AI will suggest realistic deadlines for new tasks and recommend priorities based on due dates, dependencies, and team workload.",
    status: "planned",
    category: "analytics",
    quarter: "Q4 2026",
    icon: "◮",
    badge: "Planned",
    highlights: ["Velocity-based deadline suggestions", "Priority recommendations", "Dependency-aware planning", "Workload-aware scheduling"],
  },

  // ── Future ───────────────────────────────────────────────────────────────────
  {
    id: "mobile-app",
    title: "Native Mobile App",
    description: "iOS and Android apps with offline support, push notifications, and Focus Mode.",
    detail: "A native mobile experience for Focura. Full task management, notifications, and Focus Mode on iOS and Android. Offline mode lets you view and create tasks without connectivity — changes sync automatically when back online. Push notifications replace SSE on mobile.",
    status: "future",
    category: "platform",
    quarter: "Q4 2026",
    icon: "◱",
    badge: "Future",
    highlights: ["iOS & Android", "Offline mode with sync", "Push notifications", "Focus Mode with system timer"],
  },
  {
    id: "workload-balancing",
    title: "AI Workload Balancing",
    description: "Detect overloaded team members and suggest task redistribution automatically.",
    detail: "An AI layer that monitors team workload in real time. When a member is flagged as overloaded (based on open tasks, due dates, and historical velocity), Focura suggests which tasks to redistribute and to whom — balancing workload without manager intervention.",
    status: "future",
    category: "analytics",
    quarter: "Q1 2027",
    icon: "⬟",
    badge: "Future",
    highlights: ["Real-time overload detection", "Redistribution suggestions", "Velocity-aware balancing", "Manager notification digest"],
  },
];
export const STATUS_CONFIG: Record<RoadmapStatus, {
  label: string;
  textColor: string;
  bg: string;
  border: string;
  dot: string;
}> = {
  completed: {
    label    : 'Completed',
    textColor: 'text-emerald-700 dark:text-emerald-400',
    bg       : 'bg-emerald-50 dark:bg-emerald-950/40',
    border   : 'border-emerald-200 dark:border-emerald-800/50',
    dot      : 'bg-emerald-500',
  },
  'in-progress': {
    label    : 'In Progress',
    textColor: 'text-blue-700 dark:text-blue-400',
    bg       : 'bg-blue-50 dark:bg-blue-950/40',
    border   : 'border-blue-200 dark:border-blue-800/50',
    dot      : 'bg-blue-500',
  },
  planned: {
    label    : 'Planned',
    textColor: 'text-violet-700 dark:text-violet-400',
    bg       : 'bg-violet-50 dark:bg-violet-950/40',
    border   : 'border-violet-200 dark:border-violet-800/50',
    dot      : 'bg-violet-500',
  },
  future: {
    label    : 'Future',
    textColor: 'text-neutral-500 dark:text-neutral-400',
    bg       : 'bg-neutral-100 dark:bg-neutral-800/60',
    border   : 'border-neutral-200 dark:border-neutral-700',
    dot      : 'bg-neutral-400 dark:bg-neutral-500',
  },
};

// ─── Filter options ───────────────────────────────────────────────────────────
export const FILTER_OPTIONS: { label: string; value: RoadmapStatus | 'all' }[] = [
  { label: 'All',         value: 'all'         },
  { label: 'Completed',   value: 'completed'   },
  { label: 'In Progress', value: 'in-progress' },
  { label: 'Planned',     value: 'planned'     },
  { label: 'Future',      value: 'future'      },
];
