import { FULL_BASE, type ApiSection } from '../types';

export const templatesSection: ApiSection = {
  id         : 'templates',
  title      : 'Templates',
  description: 'Public template catalog with plan-tier gating, one-click project import, save-as-template, and the template email waitlist.',
  endpoints  : [
    {
      id         : 'templates-request',
      method     : 'POST',
      path       : '/api/v1/templates',
      summary    : 'Request a template (email waitlist)',
      description: 'Public email capture for the template waitlist. Duplicate emails return 400. Rate limited (5 / 10 min).',
      auth       : 'public',
      bodyFields : [ { name: 'email', type: 'string', required: true, description: 'Valid email address' } ],
      responses  : [
        { status: 200, description: '{ success, message }' },
        { status: 400, description: 'Invalid or duplicate email' },
      ],
      examples   : [ { label: "cURL", code: "curl -X POST FULL_BASE/templates -H \"Content-Type: application/json\" -d \"{\"email\":\"you@example.com\"}\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-requests',
      method     : 'GET',
      path       : '/api/v1/templates',
      summary    : 'List template waitlist emails',
      description: 'Focura-admin only. Returns all template waitlist emails.',
      auth       : 'admin',
      responses  : [
        { status: 200, description: '[{ email }]' },
        { status: 403, description: 'Non-admin forbidden' },
      ],
      examples   : [ { label: "cURL", code: "curl FULL_BASE/templates -H \"Authorization: Bearer <token>\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-request-delete',
      method     : 'DELETE',
      path       : '/api/v1/templates/:email',
      summary    : 'Remove a waitlist email',
      description: 'Focura-admin only. Idempotent removal of a waitlist email by address.',
      auth       : 'admin',
      pathParams : [ { name: "email", type: "string", required: true, description: "Waitlist email (URL-encoded)" } ],
      responses  : [
        { status: 200, description: '{ success }' },
        { status: 403, description: 'Non-admin forbidden' },
      ],
      examples   : [ { label: "cURL", code: "curl -X DELETE FULL_BASE/templates/you%40example.com -H \"Authorization: Bearer <token>\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-catalog',
      method     : 'GET',
      path       : '/api/v1/templates/catalog',
      summary    : 'Public template catalog',
      description: 'Returns available templates plus the caller access tier (FREE/PRO/BUSINESS), resolved server-side from the workspaces the caller owns or belongs to. Supports category, tier and search filters.',
      auth       : 'public',
      queryParams: [
        { name: 'category', type: 'string', required: false, description: 'Filter by template category' },
        { name: 'tier', type: 'string', required: false, description: 'Filter by tier: FREE | PRO | BUSINESS' },
        { name: 'search', type: 'string', required: false, description: 'Free-text search on title/description' },
      ],
      responses  : [
        { status: 200, description: '{ templates, access: { tier } }' },
      ],
      examples   : [
        { label: "cURL", code: "curl FULL_BASE/templates/catalog" },
      ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-detail',
      method     : 'GET',
      path       : '/api/v1/templates/:slug',
      summary    : 'Template detail',
      description: 'Public detail for a single template by slug.',
      auth       : 'public',
      pathParams : [ { name: "slug", type: "string", required: true, description: "Template slug" } ],
      responses  : [ { status: 200, description: "Full template item" } ],
      examples   : [ { label: "cURL", code: "curl FULL_BASE/templates/engineering-sprint" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-use',
      method     : 'POST',
      path       : '/api/v1/templates/:slug/use',
      summary    : 'Import a template as a new project',
      description: 'Clones the template snapshot (sections, labels, tasks, milestones, views) into a workspace project inside a single transaction. Tier-gated by the workspace plan. Rate limited (10 / 10 min).',
      auth       : 'auth',
      pathParams : [ { name: "slug", type: "string", required: true, description: "Template slug" } ],
      bodyFields : [
        { name: 'workspaceId', type: 'string', required: true, description: 'Destination workspace' },
        { name: 'projectName', type: 'string', required: false, description: 'Optional override name' },
      ],
      responses  : [
        { status: 201, description: '{ projectSlug, workspaceSlug }' },
        { status: 403, description: 'PlanLimitError when the workspace plan is below the template tier' },
      ],
      examples   : [ { label: "cURL", code: "curl -X POST FULL_BASE/templates/engineering-sprint/use -H \"Authorization: Bearer <token>\" -H \"Content-Type: application/json\" -d \"{\"workspaceId\":\"ws_1\"}\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-rate',
      method     : 'POST',
      path       : '/api/v1/templates/:slug/rate',
      summary    : 'Rate a template (1–5 stars)',
      description: 'Authenticated users can rate a public template once — re-rating replaces their previous stars. One rating per user per template; aggregates are recomputed from the rating table.',
      auth       : 'auth',
      pathParams : [ { name: "slug", type: "string", required: true, description: "Template slug" } ],
      bodyFields : [ { name: 'stars', type: 'number', required: true, description: 'Rating between 1 and 5' } ],
      responses  : [
        { status: 200, description: '{ average, count } — updated rating summary' },
        { status: 400, description: 'Invalid stars' },
        { status: 404, description: 'Template not found' },
      ],
      examples   : [ { label: "cURL", code: "curl -X POST FULL_BASE/templates/engineering-sprint/rate -H 'Authorization: Bearer <token>' -H 'Content-Type: application/json' -d '{\"stars\":5}'" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-save',
      method     : 'POST',
      path       : '/api/v1/templates/save-as-template/:projectId',
      summary    : 'Save a project as a template',
      description: 'Snapshots a project structure (sections, labels, tasks, milestones, views) into a private workspace template. Rate limited (20 / 10 min).',
      auth       : 'auth',
      pathParams : [ { name: "projectId", type: "string", required: true, description: "Source project id" } ],
      bodyFields : [
        { name: 'title', type: 'string', required: false, description: 'Optional template title' },
        { name: 'visibility', type: 'string', required: false, description: 'PRIVATE (default) | PUBLIC' },
      ],
      responses  : [ { status: 201, description: "{ slug, title }" } ],
      examples   : [ { label: "cURL", code: "curl -X POST FULL_BASE/templates/save-as-template/proj_1 -H \"Authorization: Bearer <token>\" -H \"Content-Type: application/json\" -d \"{}\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-private',
      method     : 'GET',
      path       : '/api/v1/templates/private',
      summary    : 'Workspace private templates',
      description: 'Lists private templates saved inside a workspace (members only).',
      auth       : 'auth',
      queryParams: [ { name: "workspaceId", type: "string", required: true, description: "Workspace id" } ],
      responses  : [ { status: 200, description: "Array of private template items" } ],
      examples   : [ { label: "cURL", code: "curl \"FULL_BASE/templates/private?workspaceId=ws_1\" -H \"Authorization: Bearer <token>\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-update',
      method     : 'PATCH',
      path       : '/api/v1/templates/:slug',
      summary    : 'Update a private template',
      description: 'Update title/description/tier/etc. of a template you authored (or a Focura admin).',
      auth       : 'auth',
      pathParams : [ { name: "slug", type: "string", required: true, description: "Template slug" } ],
      responses  : [ { status: 200, description: "{ slug, title }" } ],
      examples   : [ { label: "cURL", code: "curl -X DELETE FULL_BASE/templates/tpl-1 -H \"Authorization: Bearer <token>\"" } ],
      tags       : ['templates'],
    },
    {
      id         : 'templates-delete',
      method     : 'DELETE',
      path       : '/api/v1/templates/:slug',
      summary    : 'Delete a private template',
      description: 'Deletes a template you authored (or a Focura admin).',
      auth       : 'auth',
      pathParams : [ { name: "slug", type: "string", required: true, description: "Template slug" } ],
      responses  : [ { status: 200, description: "{ success: true }" } ],
      examples   : [ { label: "cURL", code: "curl -X DELETE FULL_BASE/templates/tpl-1 -H \"Authorization: Bearer <token>\"" } ],
      tags       : ['templates'],
    },
  ],
};
